### ISSUE TITLE
2.2 regression checking

### ISSUE THREAD

**Issue by sosukesuzuki** [sosukesuzuki/prettier-regression-testing#8]
https://github.com/prettier/prettier/issues/9549

**Comment by sosukesuzuki** [comment]
run

**Comment by fisker** [comment]
Can we add  babel  project?

**Comment by sosukesuzuki** [comment]
Yes, I'll add some other projects:+1:

**Comment by sosukesuzuki** [comment]
run

**Comment by sosukesuzuki** [comment]
I think changes for babel is breaking..., Should we revert?
/cc @fisker

**Comment by fisker** [comment]
I'll take a  look in  2h.

**Comment by fisker** [comment]
v2.1.2 same result

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOA9AFRJKXklkBmEEAFDgCbozpKEC2AS2yCoAcwAKqAK5jRfPACdF6AJ4AeTDEWixAPgC+ASkIGSBkABoQEAA4xB0TMlDplEAO4S3CZynSoHmrO1gBGKmAA1nAwAMq26GC6yNrScNZw-KFwHBw5ADLo4tLoYnAAYhCK-NwO4sgg6NIwEFYgABYw-KgA6u2C8JgJYHCxvgOCAG4Dqg1g2G2imHCKMBIqYjXIjAHL1gBWmAAeAEIR0XHo-HD5onDbu+kgh0exuqhwAIrSEPAPqHsQAlFMtFA1GKhPG1bDpYD1BBwYO1kAAOAAM1hhEGWPRUtgaMLgoMm92sAEcfvB1nY-I1MABaKBwHI5NqKOAUwTs9alLZIHYAp7LIQpRRpayYd5fSn3fmPaw8ULwxHIpAAJgVKkEqF0AGEIPw+SAiQBWNrSZYAFXQoT8AsBkzSAEkoHlYLEwDp7HhXbEYKoPv9lgYDEA)
```sh
--parser flow
```

**Input:**
```jsx
class A {
  /*::*/
  foo( data: {missingPlugin: Array<string>}) {}
}
```

**Output:**
```jsx
class A {
  foo(data: { missingPlugin: Array/*:: <string> */ }) {}
}

```

**Comment by fisker** [comment]
It's broken here https://github.com/prettier/prettier/pull/8724/files#diff-0aaa38223318fb8c3d0133b3b8d8f4cbc48d37209f26f3b818398d1ccc28994aR2853

**Comment by fisker** [comment]
run with cheking out 16e33ba75c0f10c3a39f0b346ae8ef4d452124d3

**Comment by fisker** [comment]
Can I run on my fork?

**Comment by sosukesuzuki** [comment]
Sorry, current prettier-regression-testing does not support fork.

**Comment by sosukesuzuki** [comment]
run with checking out 16e33ba75c0f10c3a39f0b346ae8ef4d452124d3 on fisker/prettier

**Comment by fisker** [comment]
Run test on prettier/prettier too?

**Comment by sosukesuzuki** [comment]
> Run test on prettier/prettier too?

What do you mean?

**Comment by fisker** [comment]
Format our own codebase.

**Comment by sosukesuzuki** [comment]
I got it. I'll add it.

**Comment by sosukesuzuki** [comment]
run

**Comment by fisker** [comment]
run with checking out eff57b4 on thorn0/prettier

**Comment by fisker** [comment]
run with checking out eff57b45ff08898ee7f966d327aab9923f748872 on thorn0/prettier

**Comment by sosukesuzuki** [comment]
run

**Comment by sosukesuzuki** [comment]
2.2 has been released.
